# Generated by Django 3.0.3 on 2020-05-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200505_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sqm',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
