# Generated by Django 3.0.3 on 2020-05-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='rooms',
            new_name='room',
        ),
    ]
