# Generated by Django 3.0.3 on 2020-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_properties_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
