# Generated by Django 3.0.3 on 2020-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200507_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'Confirmed'), ('False', 'Declined')], default='New', max_length=10),
        ),
    ]
