# Generated by Django 3.0.3 on 2020-05-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_propetycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propetycomment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'Approved'), ('False', 'Declined')], default='New', max_length=10),
        ),
    ]
