# Generated by Django 3.0.3 on 2020-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200514_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propetycomment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='New', max_length=10),
        ),
    ]
