# Generated by Django 3.0.3 on 2020-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200516_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined')], default='New', max_length=10),
        ),
    ]
